[package]
name = "gnss2mesh"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
geo = "0.29.3"
geo-types = "0.7.14"
patharg = "0.4.0"
shapefile = "0.6.0"
wavefront_rs = "1.0.4"
